"""update icon column name to tag

Revision ID: 2df98b2f1c04
Revises: 11968c09cac7
Create Date: 2026-07-12 18:02:03.654237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df98b2f1c04'
down_revision: Union[str, Sequence[str], None] = '11968c09cac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('tag', sa.String(length=50), nullable=True))
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('categories', 'tag')
    # ### end Alembic commands ###
