"""added is_delete column

Revision ID: 2f1c9b5a511e
Revises: c6d2689b87ce
Create Date: 2026-07-17 08:35:21.406663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1c9b5a511e'
down_revision: Union[str, Sequence[str], None] = 'c6d2689b87ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_delete', sa.Boolean(), nullable=True,  server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_delete')
    # ### end Alembic commands ###
