"""added is_delete column in transaction

Revision ID: f1fad2482ab6
Revises: 2f1c9b5a511e
Create Date: 2026-07-19 16:57:05.975848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fad2482ab6'
down_revision: Union[str, Sequence[str], None] = '2f1c9b5a511e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_delete', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_delete')
    # ### end Alembic commands ###
